**This is a churn prediction model **
using the dataset from telco https://www.kaggle.com/datasets/blastchar/telco-customer-churn/

This is one of my first beginer projects(neural network for binary classification) and ill come back and improve on this model even further

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [46]:
import tensorflow as tf
from tensorflow.keras import layers

In [36]:
from sklearn.preprocessing import LabelEncoder

In [4]:
df = pd.read_csv('/content/Customer-Churn.csv')

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerID                  7043 non-null   object
 1   gender                      7043 non-null   object
 2   SeniorCitizen               7043 non-null   int64
 3   Partner                     7043 non-null   object
 4   Dependents                  7043 non-null   object
 5   tenure                      7043 non-null   int64
 6   PhoneService                7043 non-null   object
 7   MultipleLines               7043 non-null   object
 8   InternetService             7043 non-null   object
 9   OnlineSecurity              7043 non-null   object
 10  OnlineBackup                7043 non-null   object
 11  DeviceProtection            7043 non-null   object
 12  TechSupport                 7043 non-null   object
 13  StreamingTV                 7043 non-null   object
 14  StreamingMovies             7043 non-null   object
 15  Contract                    7043 non-null   object
 16  PaperlessBilling            7043 non-null   object
 17  PaymentMethod               7043 non-null   object
 18  MonthlyCharges              7043 non-null   float64
 19  TotalCharges                7043 non-null   object
 20  Churn                       7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [8]:
df.columns = df.columns.str.strip()

print("Column names:", df.columns)

Column names: Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [9]:
X = df.drop(columns=['customerID','Churn'])
Y = df['Churn']

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
dtypes: float64(1), int64(2), object(16)
memory usage: 1.0+ MB

In [11]:
Y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: Churn
Non-Null Count  Dtype
--------------  -----
7043 non-null   object
dtypes: object(1)
memory usage: 55.1+ KB

In [12]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [13]:
columns_to_drop = ['gender', 'Partner', 'Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod']

In [14]:
X_encoded = pd.get_dummies(X, columns=columns_to_drop, drop_first=True)

In [15]:
X_encoded.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0
1,0,34,56.95,1889.5,1,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,1,0

In [16]:
columns_to_normalize = ['tenure','MonthlyCharges','TotalCharges']

In [17]:
scaler = StandardScaler()

In [20]:
# Assuming df_encoded is your DataFrame

# Replace whitespace with NaN and then fill NaN with a default value
X_encoded['TotalCharges'] = pd.to_numeric(X_encoded['TotalCharges'].replace(' ', np.nan), errors='coerce').fillna(0)

# Convert the column to float
X_encoded['TotalCharges'] = X_encoded['TotalCharges'].astype(float)

In [23]:
X_encoded[columns_to_normalize] = scaler.fit_transform(X_encoded[columns_to_normalize])

In [24]:
X_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   SeniorCitizen                             7043 non-null   int64
 1   tenure                                    7043 non-null   float64
 2   MonthlyCharges                            7043 non-null   float64
 3   TotalCharges                              7043 non-null   float64
 4   gender_Male                               7043 non-null   uint8
 5   Partner_Yes                               7043 non-null   uint8
 6   Dependents_Yes                            7043 non-null   uint8
 7   PhoneService_Yes                          7043 non-null   uint8
 8   MultipleLines_No phone service            7043 non-null   uint8
 9   MultipleLines_Yes                         7043 non-null   uint8
 10  InternetService_Fiber optic               7043 non-null   uint8
 11  InternetService_No                        7043 non-null   uint8
 12  OnlineSecurity_No internet service        7043 non-null   uint8
 13  OnlineSecurity_Yes                        7043 non-null   uint8
 14  OnlineBackup_No internet service          7043 non-null   uint8
 15  OnlineBackup_Yes                          7043 non-null   uint8
 16  DeviceProtection_No internet service      7043 non-null   uint8
 17  DeviceProtection_Yes                      7043 non-null   uint8
 18  TechSupport_No internet service           7043 non-null   uint8
 19  TechSupport_Yes                           7043 non-null   uint8
 20  StreamingTV_No internet service           7043 non-null   uint8
 21  StreamingTV_Yes                           7043 non-null   uint8
 22  StreamingMovies_No internet service       7043 non-null   uint8
 23  StreamingMovies_Yes                       7043 non-null   uint8
 24  Contract_One year                         7043 non-null   uint8
 25  Contract_Two year                         7043 non-null   uint8
 26  PaperlessBilling_Yes                      7043 non-null   uint8
 27  PaymentMethod_Credit card (automatic)     7043 non-null   uint8
 28  PaymentMethod_Electronic check            7043 non-null   uint8
 29  PaymentMethod_Mailed check                7043 non-null   uint8
dtypes: float64(3), int64(1), uint8(26)
memory usage: 399.0 KB

In [25]:
X_train, X_temp = train_test_split(X_encoded, test_size=0.4, random_state=42)
X_dev, X_test = train_test_split(X_temp, test_size=0.5,random_state=42)

In [45]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4225 entries, 999 to 860
Data columns (total 30 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   SeniorCitizen                             4225 non-null   int64
 1   tenure                                    4225 non-null   float64
 2   MonthlyCharges                            4225 non-null   float64
 3   TotalCharges                              4225 non-null   float64
 4   gender_Male                               4225 non-null   uint8
 5   Partner_Yes                               4225 non-null   uint8
 6   Dependents_Yes                            4225 non-null   uint8
 7   PhoneService_Yes                          4225 non-null   uint8
 8   MultipleLines_No phone service            4225 non-null   uint8
 9   MultipleLines_Yes                         4225 non-null   uint8
 10  InternetService_Fiber optic               4225 non-null   uint8
 11  InternetService_No                        4225 non-null   uint8
 12  OnlineSecurity_No internet service        4225 non-null   uint8
 13  OnlineSecurity_Yes                        4225 non-null   uint8
 14  OnlineBackup_No internet service          4225 non-null   uint8
 15  OnlineBackup_Yes                          4225 non-null   uint8
 16  DeviceProtection_No internet service      4225 non-null   uint8
 17  DeviceProtection_Yes                      4225 non-null   uint8
 18  TechSupport_No internet service           4225 non-null   uint8
 19  TechSupport_Yes                           4225 non-null   uint8
 20  StreamingTV_No internet service           4225 non-null   uint8
 21  StreamingTV_Yes                           4225 non-null   uint8
 22  StreamingMovies_No internet service       4225 non-null   uint8
 23  StreamingMovies_Yes                       4225 non-null   uint8
 24  Contract_One year                         4225 non-null   uint8
 25  Contract_Two year                         4225 non-null   uint8
 26  PaperlessBilling_Yes                      4225 non-null   uint8
 27  PaymentMethod_Credit card (automatic)     4225 non-null   uint8
 28  PaymentMethod_Electronic check            4225 non-null   uint8
 29  PaymentMethod_Mailed check                4225 non-null   uint8
dtypes: float64(3), int64(1), uint8(26)
memory usage: 272.3 KB

In [ ]:
X_dev.info()

In [ ]:
X_test.info()

In [29]:
Y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: Churn
Non-Null Count  Dtype
--------------  -----
7043 non-null   object
dtypes: object(1)
memory usage: 55.1+ KB

In [37]:
label_encoder = LabelEncoder()
Y_encoded = label_encoder.fit_transform(Y)

In [38]:
Y_train, Y_temp = train_test_split(Y_encoded, test_size=0.4, random_state=42)
Y_dev, Y_test = train_test_split(Y_temp, test_size=0.5,random_state=42)

In [42]:
print(Y_train[:50])

[0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 0 1 1 1]

In [47]:
# Define the model
model = tf.keras.Sequential([
    layers.Dense(25, activation='relu', input_shape=(30,)),
    layers.Dense(15, activation='relu'),
    layers.Dense(5, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

In [48]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [49]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 25)                775

 dense_1 (Dense)             (None, 15)                390

 dense_2 (Dense)             (None, 5)                 80

 dense_3 (Dense)             (None, 1)                 6

=================================================================
Total params: 1251 (4.89 KB)
Trainable params: 1251 (4.89 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [56]:
model.fit(X_train, Y_train, epochs=10, batch_size=32, validation_data=(X_dev, Y_dev))

Epoch 1/10
133/133 [==============================] - 2s 16ms/step - loss: 0.3238 - accuracy: 0.8436 - val_loss: 0.4987 - val_accuracy: 0.7878
Epoch 2/10
133/133 [==============================] - 1s 7ms/step - loss: 0.3245 - accuracy: 0.8495 - val_loss: 0.4954 - val_accuracy: 0.7771
Epoch 3/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3235 - accuracy: 0.8492 - val_loss: 0.4939 - val_accuracy: 0.7906
Epoch 4/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3219 - accuracy: 0.8507 - val_loss: 0.4958 - val_accuracy: 0.7935
Epoch 5/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3211 - accuracy: 0.8478 - val_loss: 0.4919 - val_accuracy: 0.7928
Epoch 6/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3190 - accuracy: 0.8509 - val_loss: 0.4952 - val_accuracy: 0.7857
Epoch 7/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3215 - accuracy: 0.8509 - val_loss: 0.4987 - val_accuracy: 0.7977
Epoch 8/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3197 - accuracy: 0.8497 - val_loss: 0.4944 - val_accuracy: 0.7935
Epoch 9/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3190 - accuracy: 0.8530 - val_loss: 0.5036 - val_accuracy: 0.7935
Epoch 10/10
133/133 [==============================] - 0s 3ms/step - loss: 0.3183 - accuracy: 0.8525 - val_loss: 0.4996 - val_accuracy: 0.7892

In [57]:
# Assuming your model is already trained and stored in the 'model' variable

# Evaluate the model on the test set
test_loss, test_accuracy = model.evaluate(X_test, Y_test)

# Print the test accuracy
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")

45/45 [==============================] - 0s 3ms/step - loss: 0.5027 - accuracy: 0.7835
Test Accuracy: 78.35%

In [58]:
from sklearn.metrics import precision_score

In [61]:
Y_pred = model.predict(X_test)
Y_pred_binary = (Y_pred > 0.5).astype(int)

45/45 [==============================] - 0s 3ms/step

In [62]:
precision = precision_score(Y_test, Y_pred_binary)
print(f'Precision: {precision:.2f}')

Precision: 0.60

In [65]:
from sklearn.metrics import recall_score

# Assuming y_true and y_pred are your true and predicted labels
recall = recall_score(Y_test, Y_pred_binary)

print("Recall:", recall)

Recall: 0.5417789757412399

In [66]:
from sklearn.metrics import f1_score

f1 = f1_score(Y_test, Y_pred_binary)

print("F1 Score:",f1)

F1 Score: 0.5685997171145686